### ISSUE TITLE
Does this work with the latest version of C2?

### ISSUE THREAD

**Issue by Yellowbouncyball** [flyover/spine.js#4]
I just updated C2 and tried to use this plugin and was unable to get it to work.  When I would publish it would just render a black screen-  
https://dl.dropboxusercontent.com/u/14800164/spine_test/spine-c2-plugin-master/example/export/index.html

Any ideas? Thanks!

**Comment by flyover** [comment]
It looks like the Google Closure Compiler ADVANCED_OPTIMIZATIONS flag might be breaking things.  Can you try exporting HTML5 with "Minify script" unchecked?  I probably just need to export some of the globals.

**Comment by Yellowbouncyball** [comment]
I tried and got a similar result.  The Loader shows now, but the black screen continues-
https://dl.dropboxusercontent.com/u/14800164/spine_test/spine-c2-plugin-master/example/export/index.html

**Comment by flyover** [comment]
I've checked in a couple changes that should fix this.  Please try the latest from the spine-c2-plugin repo.

**Comment by Yellowbouncyball** [comment]
I hate to be annoying!  It still did not fix the issue.  Maybe I am stuck using Spriter...  I just love the workflow of Spine so much better.

**Comment by flyover** [comment]
Perhaps check that the plugin and export has been updated.  Delete existing and reinstall plugin and export again.
